name: Deploy Python App to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
            cd /home/ubuntu/python || exit
            git pull origin main || exit
            python3 -m pip install -r requirements.txt || exit
            pkill -f app.py || exit  # Kill any previous running Flask app
            nohup python3 app.py &  # Run Flask app in background
          EOF

      - name: Deploy Application
        run: |
          echo "Deployment Complete!"


